# Install firewalld if not present
- name: "Install firewalld"
  yum:
    name: "firewalld"
    state: "present"

# Start and enable firewalld
- service:
  name: "firewalld"
    enabled: "yes"
    state: "started"


