# Install firewalld if not present
- name: "Install firewalld"
  yum:
    name: "firewalld"
    state: "present"

# Start and enable firewalld 
- name: "Start and enable firewalld"
  service:
    name: "firewalld"
    enabled: "yes"
    state: "started"

# Allow http traffics and reload firewalld
- name: "Allow http / https"
  command: firewall-cmd --zone=dmz --permanent --add-service=http --add-service=httpsi

# Restart firewalld
- name: "Bounce firewalld"
  service:
    name: "firewalld"
    state: "restarted"
