# Create groups
- name: "Create user groups."
  group:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ user_groups }}"

# Create users account and attach and their own group list.
- name: "Create user accounts."
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    comment: "{{ item.comment }}"
  with_items: "{{ users }}"

# Copy ssh public key to user deploy
- name: "Setup authorized keys"
  authorized_key:
    key: "{{ item }}"
    user: "{{ username }}"
    state: "present"
  with_file: "{{ public_keys }}"

# Check if user is in sudoers, return 0 -> false and 1 -> true.
- name: "Check if user is already sudo without password"
  shell: 'grep "^{{ username }}" /etc/sudoers -c || true'
  register: grep_deploy_sudoers

# Allow user to run command sudo without a password
- name: "Allow user deploy to sudo without a password."
  lineinfile:
    dest: "/etc/sudoers"
    state: "present"
    insertafter : "^root"
    line: "{{ username }}\t ALL=(ALL)\t NOPASSWD: ALL"
  when: grep_deploy_sudoers.stdout == "0"

 # - name: "Disable Root Login"
 #  lineinfile:
 #    dest: "/etc/ssh/sshd_config"
 #    regexp: "^PermitRootLogin"
 #    line: "PermitRootLogin no"
 #    state: "present"
 #    backup: "yes"
 #  notify:
 #    - restart ssh
 
